/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Golden.h
  Source: D:\Work\FastCycloneDdsCsharpBindings\tests\GoldenRig\Golden.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_GOLDEN_H
#define DDSC_GOLDEN_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Golden_SimplePrimitive
{
  int32_t id;
  double value;
} Golden_SimplePrimitive;

extern const dds_topic_descriptor_t Golden_SimplePrimitive_desc;

#define Golden_SimplePrimitive__alloc() \
((Golden_SimplePrimitive*) dds_alloc (sizeof (Golden_SimplePrimitive)));

#define Golden_SimplePrimitive_free(d,o) \
dds_sample_free ((d), &Golden_SimplePrimitive_desc, (o))

typedef struct Golden_Nested
{
  int32_t a;
  double b;
} Golden_Nested;

extern const dds_topic_descriptor_t Golden_Nested_desc;

#define Golden_Nested__alloc() \
((Golden_Nested*) dds_alloc (sizeof (Golden_Nested)));

#define Golden_Nested_free(d,o) \
dds_sample_free ((d), &Golden_Nested_desc, (o))

typedef struct Golden_NestedStruct
{
  uint8_t byte_field;
  struct Golden_Nested nested;
} Golden_NestedStruct;

extern const dds_topic_descriptor_t Golden_NestedStruct_desc;

#define Golden_NestedStruct__alloc() \
((Golden_NestedStruct*) dds_alloc (sizeof (Golden_NestedStruct)));

#define Golden_NestedStruct_free(d,o) \
dds_sample_free ((d), &Golden_NestedStruct_desc, (o))

typedef struct Golden_FixedString
{
  char message[32];
} Golden_FixedString;

extern const dds_topic_descriptor_t Golden_FixedString_desc;

#define Golden_FixedString__alloc() \
((Golden_FixedString*) dds_alloc (sizeof (Golden_FixedString)));

#define Golden_FixedString_free(d,o) \
dds_sample_free ((d), &Golden_FixedString_desc, (o))

typedef struct Golden_UnboundedString
{
  int32_t id;
  char * message;
} Golden_UnboundedString;

extern const dds_topic_descriptor_t Golden_UnboundedString_desc;

#define Golden_UnboundedString__alloc() \
((Golden_UnboundedString*) dds_alloc (sizeof (Golden_UnboundedString)));

#define Golden_UnboundedString_free(d,o) \
dds_sample_free ((d), &Golden_UnboundedString_desc, (o))

#ifndef DDS_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} dds_sequence_long;

#define dds_sequence_long__alloc() \
((dds_sequence_long*) dds_alloc (sizeof (dds_sequence_long)));

#define dds_sequence_long_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
#endif /* DDS_SEQUENCE_LONG_DEFINED */

typedef struct Golden_PrimitiveSequence
{
  dds_sequence_long values;
} Golden_PrimitiveSequence;

extern const dds_topic_descriptor_t Golden_PrimitiveSequence_desc;

#define Golden_PrimitiveSequence__alloc() \
((Golden_PrimitiveSequence*) dds_alloc (sizeof (Golden_PrimitiveSequence)));

#define Golden_PrimitiveSequence_free(d,o) \
dds_sample_free ((d), &Golden_PrimitiveSequence_desc, (o))

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

typedef struct Golden_StringSequence
{
  dds_sequence_string values;
} Golden_StringSequence;

extern const dds_topic_descriptor_t Golden_StringSequence_desc;

#define Golden_StringSequence__alloc() \
((Golden_StringSequence*) dds_alloc (sizeof (Golden_StringSequence)));

#define Golden_StringSequence_free(d,o) \
dds_sample_free ((d), &Golden_StringSequence_desc, (o))

typedef struct Golden_MixedStruct
{
  uint8_t b;
  int32_t i;
  double d;
  char * s;
} Golden_MixedStruct;

extern const dds_topic_descriptor_t Golden_MixedStruct_desc;

#define Golden_MixedStruct__alloc() \
((Golden_MixedStruct*) dds_alloc (sizeof (Golden_MixedStruct)));

#define Golden_MixedStruct_free(d,o) \
dds_sample_free ((d), &Golden_MixedStruct_desc, (o))

typedef struct Golden_AppendableStruct
{
  int32_t id;
  char * message;
} Golden_AppendableStruct;

extern const dds_topic_descriptor_t Golden_AppendableStruct_desc;

#define Golden_AppendableStruct__alloc() \
((Golden_AppendableStruct*) dds_alloc (sizeof (Golden_AppendableStruct)));

#define Golden_AppendableStruct_free(d,o) \
dds_sample_free ((d), &Golden_AppendableStruct_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_GOLDEN_H */
