module Golden {
    struct SimplePrimitive {
        long id;
        double value;
    };

    struct Nested {
        long a;
        double b;
    };

    struct NestedStruct {
        octet byte_field;
        Nested nested;
    };

    struct FixedString {
        char message[32];
    };

    struct UnboundedString {
        long id;
        string message;
    };

    struct PrimitiveSequence {
        sequence<long> values;
    };

    struct StringSequence {
        sequence<string> values;
    };

    struct MixedStruct {
        octet b;
        long i;
        double d;
        string s;
    };

    @appendable
    struct AppendableStruct {
        long id;
        string message;
    };
};
