/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: D:\Work\FastCycloneDdsCsharpBindings\tests\GoldenRig/GoldenUnion.h
  Source: D:\Work\FastCycloneDdsCsharpBindings\tests\GoldenRig\GoldenUnion.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_GOLDENRIG_GOLDENUNION_H
#define DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_GOLDENRIG_GOLDENUNION_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct GoldenUnion_MyUnion
{
  int32_t _d;
  union
  {
    int32_t valueA;
    double valueB;
  } _u;
} GoldenUnion_MyUnion;

extern const dds_topic_descriptor_t GoldenUnion_MyUnion_desc;

#define GoldenUnion_MyUnion__alloc() \
((GoldenUnion_MyUnion*) dds_alloc (sizeof (GoldenUnion_MyUnion)));

#define GoldenUnion_MyUnion_free(d,o) \
dds_sample_free ((d), &GoldenUnion_MyUnion_desc, (o))

typedef struct GoldenUnion_Container
{
  struct GoldenUnion_MyUnion u;
} GoldenUnion_Container;

extern const dds_topic_descriptor_t GoldenUnion_Container_desc;

#define GoldenUnion_Container__alloc() \
((GoldenUnion_Container*) dds_alloc (sizeof (GoldenUnion_Container)));

#define GoldenUnion_Container_free(d,o) \
dds_sample_free ((d), &GoldenUnion_Container_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_D__WORK_FASTCYCLONEDDSCSHARPBINDINGS_TESTS_GOLDENRIG_GOLDENUNION_H */
