using System.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using System.Collections.Generic;

namespace CycloneDDS.CodeGen.Emitters;

public class MarshallerEmitter
{
    private readonly StringBuilder _sb = new();
    
    public string GenerateMarshaller(TypeDeclarationSyntax type, string namespaceName)
    {
        _sb.Clear();
        
        var typeName = type.Identifier.Text;
        var nativeTypeName = $"{typeName}Native";
        var marshallerTypeName = $"{typeName}Marshaller";
        
        // File header
        EmitLine("// <auto-generated/>");
        EmitLine($"// Generated marshaller for {typeName}");
        EmitLine();
        EmitLine("using System;");
        EmitLine("using System.Text;");
        EmitLine("using System.Runtime.InteropServices;");
        EmitLine("using CycloneDDS.CodeGen.Marshalling;");
        EmitLine();
        EmitLine($"namespace {namespaceName};");
        EmitLine();
        
        // Class declaration
        EmitLine($"public class {marshallerTypeName} : IMarshaller<{typeName}, {nativeTypeName}>");
        EmitLine("{");
        
        // Marshal method
        EmitLine($"    public void Marshal({typeName} managed, ref {nativeTypeName} native)");
        EmitLine("    {");
        
        var fields = type.Members.OfType<FieldDeclarationSyntax>().ToList();
        foreach (var field in fields)
        {
            EmitMarshalField(field);
        }
        
        EmitLine("    }");
        EmitLine();
        
        // Unmarshal method
        EmitLine($"    public {typeName} Unmarshal(ref {nativeTypeName} native)");
        EmitLine("    {");
        EmitLine($"        var managed = new {typeName}();");
        EmitLine();
        
        foreach (var field in fields)
        {
            EmitUnmarshalField(field);
        }
        
        EmitLine("        return managed;");
        EmitLine("    }");
        
        EmitLine("}");
        
        return _sb.ToString();
    }
    
    private void EmitMarshalField(FieldDeclarationSyntax field)
    {
        var fieldType = field.Declaration.Type.ToString();
        var fieldName = field.Declaration.Variables.FirstOrDefault()?.Identifier.Text ?? "unknown";
        
        // Primitives
        if (IsPrimitive(fieldType))
        {
            EmitLine($"        native.{fieldName} = managed.{fieldName};");
            return;
        }
        
        // FixedString
        if (fieldType.StartsWith("FixedString"))
        {
            var size = GetFixedStringSize(fieldType);
            EmitLine($"        if (managed.{fieldName} != null)");
            EmitLine("        {");
            EmitLine($"            unsafe {{ fixed (byte* ptr = native.{fieldName}) {{");
            EmitLine($"                var bytes = Encoding.UTF8.GetBytes(managed.{fieldName});");
            EmitLine($"                var len = Math.Min(bytes.Length, {size});");
            EmitLine($"                System.Runtime.InteropServices.Marshal.Copy(bytes, 0, (IntPtr)ptr, len);");
            EmitLine($"                if (len < {size}) ptr[len] = 0; // Null terminate if space allows");
            EmitLine("            } }");
            EmitLine("        }");
            return;
        }
        
        // Guid
        if (fieldType is "Guid" or "System.Guid")
        {
            EmitLine($"        unsafe {{ fixed (byte* ptr = native.{fieldName}) {{");
            EmitLine($"            *(Guid*)ptr = managed.{fieldName};");
            EmitLine("        } }");
            return;
        }
        
        // DateTime
        if (fieldType is "DateTime" or "System.DateTime")
        {
            EmitLine($"        native.{fieldName} = managed.{fieldName}.Ticks;");
            return;
        }
    }
    
    private void EmitUnmarshalField(FieldDeclarationSyntax field)
    {
        var fieldType = field.Declaration.Type.ToString();
        var fieldName = field.Declaration.Variables.FirstOrDefault()?.Identifier.Text ?? "unknown";
        
        // Primitives
        if (IsPrimitive(fieldType))
        {
            EmitLine($"        managed.{fieldName} = native.{fieldName};");
            return;
        }
        
        // FixedString
        if (fieldType.StartsWith("FixedString"))
        {
            var size = GetFixedStringSize(fieldType);
            EmitLine($"        unsafe {{ fixed (byte* ptr = native.{fieldName}) {{");
            EmitLine($"            var span = new ReadOnlySpan<byte>(ptr, {size});");
            EmitLine($"            var len = span.IndexOf((byte)0);");
            EmitLine($"            if (len == -1) len = {size};");
            EmitLine($"            managed.{fieldName} = Encoding.UTF8.GetString(ptr, len);");
            EmitLine("        } }");
            return;
        }
        
        // Guid
        if (fieldType is "Guid" or "System.Guid")
        {
            EmitLine($"        unsafe {{ fixed (byte* ptr = native.{fieldName}) {{");
            EmitLine($"            managed.{fieldName} = *(Guid*)ptr;");
            EmitLine("        } }");
            return;
        }
        
        // DateTime
        if (fieldType is "DateTime" or "System.DateTime")
        {
            EmitLine($"        managed.{fieldName} = new DateTime(native.{fieldName});");
            return;
        }
    }
    
    private bool IsPrimitive(string type)
    {
        return type is "byte" or "sbyte" or "short" or "ushort" or 
                       "int" or "uint" or "long" or "ulong" or 
                       "float" or "double" or "bool";
    }
    
    private int GetFixedStringSize(string type)
    {
        return type switch {
            "FixedString32" => 32,
            "FixedString64" => 64,
            "FixedString128" => 128,
            _ => 32
        };
    }

    private void EmitLine(string text = "")
    {
        _sb.AppendLine(text);
    }
}
