using System.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using System.Collections.Generic;

namespace CycloneDDS.CodeGen.Emitters;

public class MarshallerEmitter
{
    private readonly StringBuilder _sb = new();
    
    public string GenerateMarshaller(TypeDeclarationSyntax type, string namespaceName)
    {
        _sb.Clear();
        
        var typeName = type.Identifier.Text;
        var nativeTypeName = $"{typeName}Native";
        var marshallerTypeName = $"{typeName}Marshaller";
        
        // File header
        EmitLine("// <auto-generated/>");
        EmitLine($"// Generated marshaller for {typeName}");
        EmitLine();
        EmitLine("using System;");
        EmitLine("using System.Text;");
        EmitLine("using System.Runtime.InteropServices;");
        EmitLine("using CycloneDDS.CodeGen.Marshalling;");
        EmitLine();
        EmitLine($"namespace {namespaceName};");
        EmitLine();
        
        // Class declaration
        EmitLine($"public class {marshallerTypeName} : IMarshaller<{typeName}, {nativeTypeName}>");
        EmitLine("{");
        
        // Marshal method
        EmitLine($"    public void Marshal({typeName} managed, ref {nativeTypeName} native)");
        EmitLine("    {");
        
        var fields = type.Members.OfType<FieldDeclarationSyntax>().ToList();
        foreach (var field in fields)
        {
            EmitMarshalField(field);
        }
        
        EmitLine("    }");
        EmitLine();
        
        // Unmarshal method
        EmitLine($"    public {typeName} Unmarshal(ref {nativeTypeName} native)");
        EmitLine("    {");
        EmitLine($"        var managed = new {typeName}();");
        EmitLine();
        
        foreach (var field in fields)
        {
            EmitUnmarshalField(field);
        }
        
        EmitLine("        return managed;");
        EmitLine("    }");
        
        EmitLine("}");
        
        return _sb.ToString();
    }
    
    private void EmitMarshalField(FieldDeclarationSyntax field)
    {
        var fieldType = field.Declaration.Type.ToString();
        var fieldName = field.Declaration.Variables.FirstOrDefault()?.Identifier.Text ?? "unknown";
        
        // Primitives
        if (IsPrimitive(fieldType))
        {
            EmitLine($"        native.{fieldName} = managed.{fieldName};");
            return;
        }
        
        // FixedString
        if (fieldType.StartsWith("FixedString"))
        {
            var size = GetFixedStringSize(fieldType);
            EmitLine($"        if (managed.{fieldName} != null)");
            EmitLine("        {");
            EmitLine($"            unsafe {{ fixed (byte* ptr = native.{fieldName}) {{");
            EmitLine($"                var bytes = Encoding.UTF8.GetBytes(managed.{fieldName});");
            EmitLine($"                var len = Math.Min(bytes.Length, {size});");
            EmitLine($"                System.Runtime.InteropServices.Marshal.Copy(bytes, 0, (IntPtr)ptr, len);");
            EmitLine($"                if (len < {size}) ptr[len] = 0; // Null terminate if space allows");
            EmitLine("            } }");
            EmitLine("        }");
            return;
        }
        
        // Guid
        if (fieldType is "Guid" or "System.Guid")
        {
            EmitLine($"        unsafe {{ fixed (byte* ptr = native.{fieldName}) {{");
            EmitLine($"            *(Guid*)ptr = managed.{fieldName};");
            EmitLine("        } }");
            return;
        }
        
        // DateTime
        if (fieldType is "DateTime" or "System.DateTime")
        {
            EmitLine($"        native.{fieldName} = managed.{fieldName}.Ticks;");
            return;
        }
        
        // Arrays (unbounded)
        if (fieldType.EndsWith("[]"))
        {
            var elementType = fieldType[..^2];
            EmitLine($"        // Marshal array {fieldName}");
            EmitLine($"        if (managed.{fieldName} != null && managed.{fieldName}.Length > 0)");
            EmitLine("        {");
            
            if (IsPrimitive(elementType))
            {
                EmitLine($"            var bytes = managed.{fieldName}.Length * {GetPrimitiveSize(elementType)};");
                EmitLine($"            native.{fieldName}_Ptr = System.Runtime.InteropServices.Marshal.AllocHGlobal(bytes);");
                EmitLine($"            native.{fieldName}_Length = managed.{fieldName}.Length;");
                EmitLine($"            System.Runtime.InteropServices.Marshal.Copy(managed.{fieldName}, 0, native.{fieldName}_Ptr, managed.{fieldName}.Length);");
            }
            else
            {
                EmitLine($"            // TODO: Complex array marshalling for {elementType}");
            }
            
            EmitLine("        }");
            EmitLine("        else");
            EmitLine("        {");
            EmitLine($"            native.{fieldName}_Ptr = IntPtr.Zero;");
            EmitLine($"            native.{fieldName}_Length = 0;");
            EmitLine("        }");
            return;
        }
    }
    
    private void EmitUnmarshalField(FieldDeclarationSyntax field)
    {
        var fieldType = field.Declaration.Type.ToString();
        var fieldName = field.Declaration.Variables.FirstOrDefault()?.Identifier.Text ?? "unknown";
        
        // Primitives
        if (IsPrimitive(fieldType))
        {
            EmitLine($"        managed.{fieldName} = native.{fieldName};");
            return;
        }
        
        // FixedString
        if (fieldType.StartsWith("FixedString"))
        {
            var size = GetFixedStringSize(fieldType);
            EmitLine($"        unsafe {{ fixed (byte* ptr = native.{fieldName}) {{");
            EmitLine($"            var span = new ReadOnlySpan<byte>(ptr, {size});");
            EmitLine($"            var len = span.IndexOf((byte)0);");
            EmitLine($"            if (len == -1) len = {size};");
            EmitLine($"            managed.{fieldName} = Encoding.UTF8.GetString(ptr, len);");
            EmitLine("        } }");
            return;
        }
        
        // Guid
        if (fieldType is "Guid" or "System.Guid")
        {
            EmitLine($"        unsafe {{ fixed (byte* ptr = native.{fieldName}) {{");
            EmitLine($"            managed.{fieldName} = *(Guid*)ptr;");
            EmitLine("        } }");
            return;
        }
        
        // DateTime
        if (fieldType is "DateTime" or "System.DateTime")
        {
            EmitLine($"        managed.{fieldName} = new DateTime(native.{fieldName});");
            return;
        }
        
        // Arrays (unbounded)
        if (fieldType.EndsWith("[]"))
        {
            var elementType = fieldType[..^2];
            EmitLine($"        // Unmarshal array {fieldName}");
            EmitLine($"        if (native.{fieldName}_Ptr != IntPtr.Zero && native.{fieldName}_Length > 0)");
            EmitLine("        {");
            
            if (IsPrimitive(elementType))
            {
                EmitLine($"            managed.{fieldName} = new {elementType}[native.{fieldName}_Length];");
                EmitLine($"            System.Runtime.InteropServices.Marshal.Copy(native.{fieldName}_Ptr, managed.{fieldName}, 0, native.{fieldName}_Length);");
            }
            else
            {
                EmitLine($"            // TODO: Complex array unmarshalling for {elementType}");
            }
            
            EmitLine("        }");
            EmitLine("        else");
            EmitLine("        {");
            EmitLine($"            managed.{fieldName} = Array.Empty<{elementType}>();");
            EmitLine("        }");
            return;
        }
    }
    
    private bool IsPrimitive(string type)
    {
        return type is "byte" or "sbyte" or "short" or "ushort" or 
                       "int" or "uint" or "long" or "ulong" or 
                       "float" or "double" or "bool";
    }
    
    private int GetFixedStringSize(string type)
    {
        return type switch {
            "FixedString32" => 32,
            "FixedString64" => 64,
            "FixedString128" => 128,
            _ => 32
        };
    }

    private int GetPrimitiveSize(string type)
    {
        return type switch {
            "byte" or "sbyte" => 1,
            "short" or "ushort" => 2,
            "int" or "uint" or "float" => 4,
            "long" or "ulong" or "double" => 8,
            _ => 4
        };
    }
    
    public string GenerateUnionMarshaller(TypeDeclarationSyntax type, string namespaceName)
    {
        _sb.Clear();
        
        var typeName = type.Identifier.Text;
        var marshallerName = $"{typeName}Marshaller";
        var managedTypeName = $"{typeName}";
        var nativeTypeName = $"{typeName}Native";
        
        // Header
        EmitLine("// <auto-generated/>");
        EmitLine($"// Generated marshaller for union {typeName}");
        EmitLine();
        EmitLine("using System;");
        EmitLine("using System.Runtime.InteropServices;");
        EmitLine("using CycloneDDS.CodeGen.Marshalling;");
        EmitLine();
        EmitLine($"namespace {namespaceName};");
        EmitLine();
        
        EmitLine($"public class {marshallerName} : IMarshaller<{managedTypeName}, {nativeTypeName}>");
        EmitLine("{");
        
        // Marshal
        EmitLine($"    public void Marshal({managedTypeName} managed, ref {nativeTypeName} native)");
        EmitLine("    {");
        
        // Marshal discriminator
        var discriminatorField = type.Members.OfType<FieldDeclarationSyntax>()
            .First(f => f.AttributeLists.SelectMany(al => al.Attributes)
                .Any(attr => attr.Name.ToString().Contains("Discriminator")));
        
        var discName = discriminatorField.Declaration.Variables.First().Identifier.Text;
        EmitLine($"        native.{discName} = managed.{discName};");
        EmitLine();
        
        // Switch on discriminator
        EmitLine($"        switch (managed.{discName})");
        EmitLine("        {");
        
        var caseFields = type.Members.OfType<FieldDeclarationSyntax>()
            .Where(f => f.AttributeLists.SelectMany(al => al.Attributes)
                .Any(attr => attr.Name.ToString().Contains("DdsCase")));
        
        foreach (var caseField in caseFields)
        {
            var armName = caseField.Declaration.Variables.First().Identifier.Text;
            var caseAttr = caseField.AttributeLists.SelectMany(al => al.Attributes)
                .First(attr => attr.Name.ToString().Contains("DdsCase"));
            var caseValue = caseAttr.ArgumentList?.Arguments.FirstOrDefault()?.ToString() ?? "0";
            
            EmitLine($"            case {caseValue}:");
            EmitLine($"                native.{armName} = managed.{armName};");
            EmitLine("                break;");
        }
        
        EmitLine("        }");
        EmitLine("    }");
        EmitLine();
        
        // Unmarshal
        EmitLine($"    public {managedTypeName} Unmarshal(ref {nativeTypeName} native)");
        EmitLine("    {");
        EmitLine($"        var managed = new {managedTypeName}();");
        EmitLine($"        managed.{discName} = native.{discName};");
        EmitLine();
        EmitLine($"        switch (native.{discName})");
        EmitLine("        {");
        
        foreach (var caseField in caseFields)
        {
            var armName = caseField.Declaration.Variables.First().Identifier.Text;
            var caseAttr = caseField.AttributeLists.SelectMany(al => al.Attributes)
                .First(attr => attr.Name.ToString().Contains("DdsCase"));
            var caseValue = caseAttr.ArgumentList?.Arguments.FirstOrDefault()?.ToString() ?? "0";
            
            EmitLine($"            case {caseValue}:");
            EmitLine($"                managed.{armName} = native.{armName};");
            EmitLine("                break;");
        }
        
        EmitLine("        }");
        EmitLine("        return managed;");
        EmitLine("    }");
        
        EmitLine("}");
        
        return _sb.ToString();
    }

    private void EmitLine(string text = "")
    {
        _sb.AppendLine(text);
    }
}
