using System.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using System.Collections.Generic;

namespace CycloneDDS.CodeGen.Emitters;

public class MetadataRegistryEmitter
{
    private readonly StringBuilder _sb = new();
    
    public string GenerateRegistry(List<(TypeDeclarationSyntax Type, string TopicName)> topics, string namespaceName)
    {
        _sb.Clear();
        
        EmitLine("// <auto-generated/>");
        EmitLine("// Generated metadata registry");
        EmitLine();
        EmitLine("using System;");
        EmitLine("using System.Collections.Generic;");
        EmitLine("using CycloneDDS.CodeGen.Marshalling;");
        EmitLine();
        EmitLine($"namespace {namespaceName};");
        EmitLine();
        
        EmitLine("public static class MetadataRegistry");
        EmitLine("{");
        EmitLine("    private static readonly Dictionary<string, TopicMetadata> _registry = new()");
        EmitLine("    {");
        
        foreach (var (type, topicName) in topics)
        {
            var typeName = type.Identifier.Text;
            
            // Find key fields
            var keyFields = type.Members.OfType<FieldDeclarationSyntax>()
                .Select((f, idx) => new { Field = f, Index = idx })
                .Where(x => x.Field.AttributeLists
                    .SelectMany(al => al.Attributes)
                    .Any(attr => attr.Name.ToString().Contains("DdsKey")))
                .Select(x => x.Index)
                .ToArray();
            
            var keyIndicesStr = keyFields.Length > 0 
                ? $"new[] {{ {string.Join(", ", keyFields)} }}" 
                : "Array.Empty<int>()";
            
            EmitLine($"        {{ \"{topicName}\", new TopicMetadata");
            EmitLine("        {");
            EmitLine($"            TopicName = \"{topicName}\",");
            EmitLine($"            TypeName = \"{typeName}\",");
            EmitLine($"            ManagedType = typeof({typeName}),");
            EmitLine($"            NativeType = typeof({typeName}Native),");
            EmitLine($"            MarshallerType = typeof({typeName}Marshaller),");
            EmitLine($"            KeyFieldIndices = {keyIndicesStr}");
            EmitLine("        }},");
        }
        
        EmitLine("    };");
        EmitLine();
        EmitLine("    public static TopicMetadata GetMetadata(string topicName) => _registry[topicName];");
        EmitLine("    public static bool TryGetMetadata(string topicName, out TopicMetadata? metadata) => _registry.TryGetValue(topicName, out metadata);");
        EmitLine("    public static IEnumerable<TopicMetadata> GetAllTopics() => _registry.Values;");
        EmitLine("}");
        
        return _sb.ToString();
    }
    
    private void EmitLine(string text = "") => _sb.AppendLine(text);
}
