// <auto-generated from Cyclone DDS source>
// Cyclone DDS Version: 0.11.0
// Generated: 2026-01-15 23:40:18 UTC

namespace CycloneDDS.Runtime.Descriptors;

/// <summary>
/// ABI offsets for dds_topic_descriptor_t.
/// Auto-generated from Cyclone DDS source code.
/// </summary>
public static class AbiOffsets
{
    public const string CycloneVersion = "0.11.0";

    public const int Size = 0;
    public const int Align = 4;
    public const int Flagset = 8;
    public const int NKeys = 12;
    public const int TypeName = 16;
    public const int Keys = 24;
    public const int NOps = 32;
    public const int Ops = 40;
    public const int Meta = 48;
    public const int TypeInfo = 56;
    public const int TypeInfo_Data = 56;
    public const int TypeInfo_Size = 64;
    public const int TypeMap = 72;
    public const int TypeMap_Data = 72;
    public const int TypeMap_Size = 80;

    public const int DescriptorSize = 96;
}
